DROP SCHEMA public CASCADE;
CREATE SCHEMA public;

/* Tipos */
CREATE TYPE TIPO_CARRERA AS ENUM('EVENTO', 'CIRCUITO');
CREATE TYPE TIPO_CONTROL AS ENUM('SALIDA', 'CONTROL', 'META');
CREATE TYPE MODALIDAD AS ENUM('TRAZADO', 'SCORE');

/* Cast para inserción de controles */
CREATE CAST (CHARACTER VARYING AS TIPO_CONTROL) WITH INOUT AS IMPLICIT;

/* Tablas */
CREATE TABLE IF NOT EXISTS USUARIOS (
	ID SERIAL,
	NOMBRE VARCHAR(30) NOT NULL UNIQUE,
	EMAIL VARCHAR(100) NOT NULL UNIQUE,
	CLUB VARCHAR(30),
	PASSWORD VARCHAR(64) NOT NULL,
	FECHA_REGISTRO DATE NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS CARRERAS (
	ID SERIAL,
	SECRET VARCHAR(32) NOT NULL,
	NOMBRE VARCHAR(64) NOT NULL,
	TIPO TIPO_CARRERA NOT NULL,
	MODALIDAD MODALIDAD NOT NULL,
	ORGANIZADOR_ID INTEGER REFERENCES USUARIOS(ID),
	PRIVADA BOOLEAN NOT NULL DEFAULT FALSE,
	LATITUD REAL,
	LONGITUD REAL,
	NOTAS VARCHAR(1000),
	FECHA DATE DEFAULT CURRENT_DATE,
	PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS RECORRIDOS (
	ID SERIAL,
	NOMBRE TEXT NOT NULL,
	CARRERA_ID INTEGER NOT NULL REFERENCES CARRERAS(ID) ON DELETE CASCADE,
	MAPA BYTEA,
	PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS CONTROLES (
	ID SERIAL,
	CODIGO TEXT NOT NULL,
	CARRERA_ID INTEGER NOT NULL REFERENCES CARRERAS(ID) ON DELETE CASCADE,
	TIPO TIPO_CONTROL NOT NULL,
	PUNTUACION INTEGER,
	COORD_X REAL,
	COORD_Y REAL,
	PRIMARY KEY (ID),
	UNIQUE (CODIGO, CARRERA_ID)
);

CREATE TABLE IF NOT EXISTS CONTROLES_RECORRIDO (
	RECORRIDO_ID INTEGER REFERENCES RECORRIDOS(ID) ON DELETE CASCADE,
	ORDEN SMALLINT,
	CONTROL_CODIGO TEXT,
	PRIMARY KEY(RECORRIDO_ID, ORDEN)
);

CREATE TABLE IF NOT EXISTS REGISTROS (
	ID SERIAL,
	CORREDOR_ID INTEGER NOT NULL REFERENCES USUARIOS(ID) ON DELETE CASCADE,
	CONTROL_ID INTEGER NOT NULL REFERENCES CONTROLES(ID) ON DELETE CASCADE,
	RECORRIDO_ID INTEGER NOT NULL REFERENCES RECORRIDOS(ID) ON DELETE CASCADE,
	FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (ID),
	UNIQUE (CORREDOR_ID, CONTROL_ID, RECORRIDO_ID, FECHA)
);
