DROP SCHEMA public CASCADE;
CREATE SCHEMA public;

/* Tipos */
CREATE TYPE TIPO_CARRERA AS ENUM('EVENTO', 'CIRCUITO');
CREATE TYPE TIPO_CONTROL AS ENUM('SALIDA', 'CONTROL', 'META');
CREATE TYPE MODALIDAD AS ENUM('LINEA', 'SCORE');

/* Cast para inserción de controles */
CREATE CAST (CHARACTER VARYING AS TIPO_CONTROL) WITH INOUT AS IMPLICIT;

/* Tablas */
CREATE TABLE IF NOT EXISTS USUARIOS (
	ID SERIAL PRIMARY KEY,
	NOMBRE TEXT NOT NULL UNIQUE,
	EMAIL TEXT NOT NULL UNIQUE,
	PASSWORD TEXT NOT NULL,
	FECHA_REGISTRO DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS CARRERAS (
	ID SERIAL,
	SECRET TEXT NOT NULL,
	NOMBRE TEXT NOT NULL,
	TIPO TIPO_CARRERA NOT NULL,
	MODALIDAD MODALIDAD NOT NULL,
	ORGANIZADOR_ID INTEGER REFERENCES USUARIOS(ID),
	PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS RECORRIDOS (
	ID SERIAL,
	NOMBRE TEXT NOT NULL,
	CARRERA_ID INTEGER REFERENCES CARRERAS(ID) ON DELETE CASCADE,
	PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS CONTROLES (
	CODIGO TEXT NOT NULL,
	CARRERA_ID INTEGER REFERENCES CARRERAS(ID) ON DELETE CASCADE,
	TIPO TIPO_CONTROL NOT NULL,
	PRIMARY KEY (CODIGO, CARRERA_ID)
);

CREATE TABLE IF NOT EXISTS CONTROLES_RECORRIDO (
	RECORRIDO_ID INTEGER REFERENCES RECORRIDOS(ID) ON DELETE CASCADE,
	ORDEN SMALLINT NOT NULL,
	CODIGO_CONTROL TEXT,
	PRIMARY KEY(RECORRIDO_ID, ORDEN)
);


/**** DATOS DE PRUEBA ****/
ALTER SEQUENCE carreras_id_seq restart with 2;
INSERT INTO USUARIOS(ID, NOMBRE, EMAIL, PASSWORD, FECHA_REGISTRO) VALUES (1, 'Pepito Pérez', 'pepito@test.com', '<redacted>', '2020-06-18');

INSERT INTO CARRERAS(ID, SECRET, NOMBRE, TIPO, MODALIDAD, ORGANIZADOR_ID) VALUES (1, 'not-a-real-secret', 'Prueba de carrera', 'EVENTO', 'LINEA', 1);

INSERT INTO RECORRIDOS(NOMBRE, CARRERA_ID) VALUES ('OPEN AMARILLO', 1);
INSERT INTO RECORRIDOS(NOMBRE, CARRERA_ID) VALUES ('OPEN NARANJA', 1);
INSERT INTO RECORRIDOS(NOMBRE, CARRERA_ID) VALUES ('OPEN ROJO', 1);

INSERT INTO CONTROLES(CODIGO, CARRERA_ID, TIPO) VALUES ('S1', 1, 'SALIDA');
INSERT INTO CONTROLES(CODIGO, CARRERA_ID, TIPO) VALUES ('31', 1, 'CONTROL');
INSERT INTO CONTROLES(CODIGO, CARRERA_ID, TIPO) VALUES ('32', 1, 'CONTROL');
INSERT INTO CONTROLES(CODIGO, CARRERA_ID, TIPO) VALUES ('33', 1, 'CONTROL');
INSERT INTO CONTROLES(CODIGO, CARRERA_ID, TIPO) VALUES ('M1', 1, 'META');

/* Open amarillo */
INSERT INTO CONTROLES_RECORRIDO(RECORRIDO_ID, ORDEN, CODIGO_CONTROL) VALUES (1, 0, 'S1'); -- S1
INSERT INTO CONTROLES_RECORRIDO(RECORRIDO_ID, ORDEN, CODIGO_CONTROL) VALUES (1, 1, '31'); -- 31
INSERT INTO CONTROLES_RECORRIDO(RECORRIDO_ID, ORDEN, CODIGO_CONTROL) VALUES (1, 2, '33'); -- 33
INSERT INTO CONTROLES_RECORRIDO(RECORRIDO_ID, ORDEN, CODIGO_CONTROL) VALUES (1, 3, 'M1'); -- M1
/* Open naranja */
INSERT INTO CONTROLES_RECORRIDO(RECORRIDO_ID, ORDEN, CODIGO_CONTROL) VALUES (2, 0, 'S1'); -- S1
INSERT INTO CONTROLES_RECORRIDO(RECORRIDO_ID, ORDEN, CODIGO_CONTROL) VALUES (2, 1, '32'); -- 32
INSERT INTO CONTROLES_RECORRIDO(RECORRIDO_ID, ORDEN, CODIGO_CONTROL) VALUES (2, 2, '31'); -- 31
INSERT INTO CONTROLES_RECORRIDO(RECORRIDO_ID, ORDEN, CODIGO_CONTROL) VALUES (2, 3, '33'); -- 33
INSERT INTO CONTROLES_RECORRIDO(RECORRIDO_ID, ORDEN, CODIGO_CONTROL) VALUES (2, 4, 'M1'); -- M1